# Introduction to Python: Dataframes

Nearly all researchers work with tabular data at one time or another. In this lesson, we will practice with **dataframes**, a Python data structure designed to work with tabular data, using the **Pandas library**. We will create our own dataframes, read in data from .csv files to a dataframe, subset and combine dataframes, and add or modify columns (variables) and observations (rows). We will also examine how these tasks work with messy and large datasets (i.e. millions or rows).

To learn more about Pandas, visit the webpage for the [Pandas library](https://pandas.pydata.org/).

For further practice with Python and Pandas dataframes, visit:

1. Software Carpentries [Pandas DataFrames](http://swcarpentry.github.io/python-novice-gapminder/08-data-frames/index.html) lesson.
2. The **Pandas basics** and **intermediate** [tutorials offered by Constellate](https://github.com/ithaka/constellate-notebooks/tree/master).
3. Chapter 3, ["Data Analysis (Pandas)"](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html) in Melanie Walsh's *Introduction to Cultural Analytics & Python*.

Note: All three platforms above offer excellent lessons for learning how to perform various other tasks in Python. Check them out.

Finally, don't worry about memorizing all the functions and syntax needed to work with Pandas. You can use the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf) as a handy guide to remind you of some of these key functions.


<h2 style="text-align:center;font-size:300%;">Dataframes: The Basics<h1> 
  <img src="https://media.geeksforgeeks.org/wp-content/cdn-uploads/creating_dataframe1.png" style="width:%40;">

A dataframe is a particular data structure that includes:
+ **rows** that record each observation of data
+ **columns** that record different attributes / measures / variables for each observation
+ **column labels** that describe the data recorded in each column
+ **index labels** that differentiate between each observations

## I. Create a dataframe

1. First, we need to import the [**Pandas**, Python's data analysis library](https://pandas.pydata.org/) that allows us to work with dataframes. It is almost universal practice among Python users to import Pandas under the name "pd" to serve as a useful abbreviation we can use when calling Pandas functions. We will also import **pathlib** and **glob** to help us work with file paths.

In [724]:
import pandas as pd
import pathlib, glob
from pathlib import Path

2. There are many ways to create a dataframe:
    +  Perhaps the most common way is to **load an existing dataset saved as a *.csv*** (Comma Separated Values) file and read it in directly as a Pandas dataframe. We will introduce that method in the next section.
    +  **Import data from other files and convert it into a dataframe.** For example, you could write a Python script iterating over 1000s of text files and create a Pandas dataframe with basic information about each text (i.e. file names, number of words, etc.)
    + **We can also create a dataframe from scratch** (usually only used to demo or practice with dataframes):

In [725]:
# this example comes from Constellate's Pandas 1 tutorial
  ## https://lab.constellate.org/ilr-review-primary/notebooks/tdm-notebooks-2023-04-19T13%3A37%3A13.281Z/pandas-1.ipynb
wcup = pd.DataFrame({"Year": [2022, 
                              2018, 
                              2014, 
                              2010, 
                              2006, 
                              2002, 
                              1998, 
                              1994, 
                              1990,
                              1986], 
                     "Champion": ["Argentina", 
                                  "France", 
                                  "Germany", 
                                  "Spain", 
                                  "Italy", 
                                  "Brazil", 
                                  "France", 
                                  "Brazil", 
                                  "Germany", 
                                  "Argentina"], 
                     "Host": ["Qatar", 
                              "Russia", 
                              "Brazil", 
                              "South Africa", 
                              "Germany", 
                              "Korea/Japan", 
                              "France", 
                              "USA", 
                              "Italy", 
                              "Mexico"]
                    })

3. In the above example, we are directly inputting a dataframe using the Python **dictionary** data structure. For more on Python dictionaries (click here)[https://www.w3schools.com/python/python_dictionaries.asp]. 

*This is beyond the scope of this lesson, but if you are curious, you can learn more about Python dictionaries from [w3schools](https://www.w3schools.com/python/python_dictionaries.asp) or [GeeksforGeeks](https://www.geeksforgeeks.org/python-dictionary/)*

Let's view what the resulting dataframe looks like by typing the variable name we used to save our World Cup dataframe into memory:

In [726]:
wcup

   Year   Champion          Host
0  2022  Argentina         Qatar
1  2018     France        Russia
2  2014    Germany        Brazil
3  2010      Spain  South Africa
4  2006      Italy       Germany
5  2002     Brazil   Korea/Japan
6  1998     France        France
7  1994     Brazil           USA
8  1990    Germany         Italy
9  1986  Argentina        Mexico

We will come back to this dataset below.

## II. Read a Dataframe

Besides the basic Men's World Cup dataset created above, in this lesson we will also be working with:
 
+ the famous Gapminder dataset charting changing life expectancies and GDP values for countries over time. (used by Software Carpentries)
<!--+ The Bellevue Almshouse dataset (used in [Walsh, *Intro to Cultural Analytics*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html) and created by Anelise Hanson Shrout. Original [link to data here](https://docs.google.com/spreadsheets/d/1uf8uaqicknrn0a6STWrVfVMScQQMtzYf5I_QyhB9r7I/edit#gid=2057113261). An [essay about this dataset is here](https://crdh.rrchnm.org/essays/v01-10-(re)-humanizing-data/).)-->
+ Hollywood Film Dialogue dataset (also used in Walsh. Original data from Hannah Anderson and Matt Daniels, ["Film Dialogue from 2,000 screenplays, Broken down by Gender and Age."](https://pudding.cool/2017/03/film-dialogue/))

4. To read data in, we will use the Pandas [**read_csv** function](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html). First, however, we need to create a path to the folder where our datasets are saved. We will use the **Path** function from the **pathlib** library.

In [727]:
Path.cwd()

WindowsPath('c:/Users/F0040RP/Documents/DartLib_RDS/python_workshops/py-essentials_ws/lessons/02_dataframes/code')

In [728]:
gapminder_df = pd.read_csv("../../../data/gapminder.csv")

We can print out the first 5 rows of this dataframe using the **.head()** method. *Methods* are functions which are applied only to specified data types. I.e. "string methods" are those functions that only work on text strings.

In [729]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

Here is a quick summary of what you see above from Melanie Walsh's online book, [*Introduction to Cultural Analytics & Python*](https://melaniewalsh.github.io/Intro-Cultural-Analytics/03-Data-Analysis/01-Pandas-Basics-Part1.html):

There are a few important things to note about the DataFrame displayed here:

+ Index
    - The bolded ascending numbers in the very left-hand column of the DataFrame is called the Pandas Index. You can select rows based on the Index.
    - By default, the Index is a sequence of numbers starting with zero. However, you can change the Index to something else, such as one of the columns in your dataset.

+ Truncation
    - The DataFrame is truncated, signaled by the ellipses in the middle ... of every column.
    - The DataFrame is truncated because we set our default display settings to 100 rows. Anything more than 100 rows will be truncated. To display all the rows, we would need to alter Pandas’ default display settings yet again.

+ Rows x Columns
    - Pandas reports how many rows and columns are in this dataset at the bottom of the output (n rows x n columns).
    - This is very useful!

*In addition, I would also add that in the preview of the dataframe above - at least as viewed within JHub - you can click on a pen/highlighter icon to view the whole dataframe.*

## III. Get summary data to learn more about a dataframe

6. Now, often the first thing we want to do with a new dataset is to explore the size of the dataset and the type and range of data it contains. Pandas dataframes come with a variety of built-in methods designed to explore dataframes. These include:
   
   ```
   # syntax: dateframe_name.method()

   .head()
   .tail()
   .shape
   .info()
   .sample()
   .describe()
   .columns()
   .value_counts()
   ```
   
7. Run the following functions and then use hashtags ```#``` to add in comments about what each does.

In [730]:
gapminder_df.head(12)  #

        country continent  year  lifeExp       pop  gdpPercap
0   Afghanistan      Asia  1952    28.80   8425333     779.45
1   Afghanistan      Asia  1957    30.33   9240934     820.85
2   Afghanistan      Asia  1962    32.00  10267083     853.10
3   Afghanistan      Asia  1967    34.02  11537966     836.20
4   Afghanistan      Asia  1972    36.09  13079460     739.98
5   Afghanistan      Asia  1977    38.44  14880372     786.11
6   Afghanistan      Asia  1982    39.85  12881816     978.01
7   Afghanistan      Asia  1987    40.82  13867957     852.40
8   Afghanistan      Asia  1992    41.67  16317921     649.34
9   Afghanistan      Asia  1997    41.76  22227415     635.34
10  Afghanistan      Asia  2002    42.13  25268405     726.73
11  Afghanistan      Asia  2007    43.83  31889923     974.58

In [731]:
gapminder_df.tail() #

       country continent  year  lifeExp       pop  gdpPercap
1699  Zimbabwe    Africa  1987    62.35   9216418     706.16
1700  Zimbabwe    Africa  1992    60.38  10704340     693.42
1701  Zimbabwe    Africa  1997    46.81  11404948     792.45
1702  Zimbabwe    Africa  2002    39.99  11926563     672.04
1703  Zimbabwe    Africa  2007    43.49  12311143     469.71

In [732]:
gapminder_df.shape #

(1704, 6)

In [733]:
gapminder_df.info() #

<class 'pandas.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    1704 non-null   str
 1   continent  1704 non-null   str
 2   year       1704 non-null   int64
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), str(2)
memory usage: 80.0 KB

In [734]:
gapminder_df.sample(10) #

               country continent  year  lifeExp       pop  gdpPercap
837   Korea, Dem. Rep.      Asia  1997    67.73  21585105    1690.76
604          Guatemala  Americas  1972    53.74   5149581    4031.41
1568           Tunisia    Africa  1992    70.00   8523077    4332.72
251             Canada  Americas  2007    80.65  33390141   36319.24
134            Bolivia  Americas  1962    43.43   3593918    2180.97
394               Cuba  Americas  2002    77.16  11226999    6340.65
990             Mexico  Americas  1982    67.41  71640904    9611.15
986             Mexico  Americas  1962    58.30  41121485    4581.61
1648           Vietnam      Asia  1972    50.25  44655014     699.50
131              Benin    Africa  2007    56.73   8078314    1441.28

In [735]:
gapminder_df.describe() #

         year  lifeExp           pop  gdpPercap
count 1704.00  1704.00       1704.00    1704.00
mean  1979.50    59.47   29601212.32    7215.33
std     17.27    12.92  106157896.74    9857.45
min   1952.00    23.60      60011.00     241.17
25%   1965.75    48.20    2793664.00    1202.06
50%   1979.50    60.71    7023595.50    3531.85
75%   1993.25    70.85   19585221.75    9325.46
max   2007.00    82.60 1318683096.00  113523.13

In [736]:
gapminder_df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

In [737]:
## We can also get summary information about individual columns. For example:
pd.options.display.float_format = '{:.2f}'.format
gapminder_df['gdpPercap'].describe()

count     1704.00
mean      7215.33
std       9857.45
min        241.17
25%       1202.06
50%       3531.85
75%       9325.46
max     113523.13
Name: gdpPercap, dtype: float64

Let's see what happens when we apply **.describe()** to a column filled with categorical data:

In [738]:
gapminder_df['continent'].describe()

count       1704
unique         5
top       Africa
freq         624
Name: continent, dtype: object

In [739]:
## or:
gapminder_df['continent'].value_counts()

continent
Africa      624
Asia        396
Europe      360
Americas    300
Oceania      24
Name: count, dtype: int64

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercises for Parts II and III</h3>

<p style="color:blue;">7. Take a look at the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf). Are there any other summary data you would like to retrieve from this dataset. Try it below:</p></div>

<div class="alert alert-info" role="alert"><p style="color:blue;">8. Now let's open the Film Dialogue dataset. Copy and paste the code from Part II, Numbers 4 and 5 below and then modify that code to open the film dialogue dataset. (Navigate to the film-dialogue folder using the folder directory on the left. You will need to identify the specific file path to and file name of the film dataframe).</p>
</div>

In [740]:
#film_path = Path("~/shared/RR-workshop-data/film-dialogue").expanduser() 
#film_dialogue_df = pd.read_csv(Path(film_path, "Pudding-Film-Dialogue-Clean.csv"))
film_dialogue_df = pd.read_csv("../../../data/Merged-Pudding-Film-Dialogue.csv")
film_dialogue_df.head()

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
0,280,betty,311,f,35.00,tt0112579,The Bridges of Madison County,1995,142.00,0.05
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.14
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.02
3,280,francesca johns,2251,f,46.00,tt0112579,The Bridges of Madison County,1995,142.00,0.35
4,280,madge,190,f,46.00,tt0112579,The Bridges of Madison County,1995,142.00,0.03

\*\***A note about data entry and humans (and things like gender, race, class, etc.)**: When people collect data, they often have to reduce complex phenomena to individual categories. This is problematic when performed on objects that do not neatly fit into pre-existing categories (or any categories for that matter). This is especially problematic when assigned to humans. How do you reduce humans to a racial or ethnic category when those categories are, to at least some extent, social inventions? When a person comes from a mixed background? How do you reduce people to two gender categories, when many people do not feel they are adequately represented by such categories? Keep this in mind when reviewing datasets that place people into hard and fast categories (as the above dataset does for the gender of movie characters).

<div class="alert alert-info" role="alert"><p style="color:blue;">9. Using some of the methods introduced in Part III and the [Python Pandas Cheat Sheet](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf), answer the following questions:</p>
<ul>
    <li style="color:blue;">How many rows and columns are there in this dataset?</li>
</ul>
</div>

In [741]:
film_dialogue_df.shape

(23048, 10)

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">What are the range of dates for the films included in this dataset?</li>
</ul>
</div>

In [742]:
film_dialogue_df.describe()

       script_id    words      age     year    gross  proportion_of_dialogue
count   23048.00 23048.00 18263.00 23048.00 19387.00                23048.00
mean     4194.78   907.87    42.38  1998.13   106.74                    0.09
std      2472.99  1399.59    59.72    14.75   145.86                    0.11
min       280.00   101.00     3.00  1929.00     0.00                    0.00
25%      2095.00   193.00    30.00  1992.00    22.00                    0.02
50%      3694.00   396.00    39.00  2001.00    56.00                    0.04
75%      6219.75   980.00    50.00  2009.00   136.00                    0.10
max      9254.00 28102.00  2013.00  2015.00  1798.00                    0.92

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">How many men vs. women (** - see note above) are included in this dataset</li>
</ul>
</div>

In [743]:
film_dialogue_df['gender'].value_counts()

gender
m    16132
f     6911
?        5
Name: count, dtype: int64

<div class="alert alert-info" role="alert">
<ul>
    <li style="color:blue;">What is the average age of film characters in this dataset?</li>

</ul>
</div>

In [744]:
film_dialogue_df['age'].describe()

count   18263.00
mean       42.38
std        59.72
min         3.00
25%        30.00
50%        39.00
75%        50.00
max      2013.00
Name: age, dtype: float64

## IV. Access Parts of a Data Frame

<div class="alert alert-success" role="alert"><p style="color:green">10. Let's take a look at our Gapminder data again. Use the **.head()** method to output the first 5 rows of this dataset (wcup).</p></div>

In [745]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

11. We can use the **.iloc[..., ...]** method to extract particular columns, rows, or cells. For example to retrieve the first row or first column, we would do the following:

In [746]:
gapminder_df.iloc[0]

country      Afghanistan
continent           Asia
year                1952
lifeExp            28.80
pop              8425333
gdpPercap         779.45
Name: 0, dtype: object

In [747]:
gapminder_df.iloc[:,0]

0       Afghanistan
1       Afghanistan
2       Afghanistan
3       Afghanistan
4       Afghanistan
           ...
1699       Zimbabwe
1700       Zimbabwe
1701       Zimbabwe
1702       Zimbabwe
1703       Zimbabwe
Name: country, Length: 1704, dtype: str

<div class="alert alert-success" role="alert"><p style="color:green">11b. Can you guess how to extract only the last column?</p></div>

In [748]:
gapminder_df.iloc[:,-1]

0      779.45
1      820.85
2      853.10
3      836.20
4      739.98
        ...
1699   706.16
1700   693.42
1701   792.45
1702   672.04
1703   469.71
Name: gdpPercap, Length: 1704, dtype: float64

<div class="alert alert-success" role="alert"><p style="color:green">11c. How would you retrieve the value found in the 2nd row of the 2nd column?</p></div>

In [749]:
gapminder_df.iloc[1,1]  #remember the 1st item of a list or series in Python is number 0. Thus, the second item is number 1.

'Asia'

12. We can us **.loc[..., ...]** to retrieve values, columns, or rows by their labels. For example, if we wanted to retrieve all info from the "Champion" column, we would simply run:

In [750]:
gapminder_df.loc[:,"year"].unique()

array([1952, 1957, 1962, 1967, 1972, 1977, 1982, 1987, 1992, 1997, 2002,
       2007])

12d. Like many things in Python, there are often multiple ways to accomplish the same goal. For example, we can also select particular columns by simply placing the names of a column within brackets (similar to indexing and slicing lists in Python).

In [751]:
# Use bracket notation to access the column 'Champion'
gapminder_df['continent']

0         Asia
1         Asia
2         Asia
3         Asia
4         Asia
         ...
1699    Africa
1700    Africa
1701    Africa
1702    Africa
1703    Africa
Name: continent, Length: 1704, dtype: str

In [752]:
# Access multiple columns
# film_dialogue_df[["title", "character", "age"]]
gapminder_df[["country", "continent"]]

          country continent
0     Afghanistan      Asia
1     Afghanistan      Asia
2     Afghanistan      Asia
3     Afghanistan      Asia
4     Afghanistan      Asia
...           ...       ...
1699     Zimbabwe    Africa
1700     Zimbabwe    Africa
1701     Zimbabwe    Africa
1702     Zimbabwe    Africa
1703     Zimbabwe    Africa

[1704 rows x 2 columns]

## V. Subset, Filter, and Sort a Dataframe

Frequently, when we are working with a dataset we may want to subset, filter, or sort the dataset before beginning your analysis.

Many of you may already be familiar with subsetting, filtering, and sorting datasets. But, just for review, this is what we mean by these terms:
+ **subset** - to subset a dataset is to create a smaller version of the dataset. For example, you may want to drop specific columns or rows to create a dataframe for your analysis

    <img src="https://pandas.pydata.org/docs/_images/03_subset_columns.svg" style="width:40%;">
    <img src="https://pandas.pydata.org/docs/_images/03_subset_rows.svg" style="width:40%;">
    
    + **filter** - filtering a dataframe is a specific type of subsetting. For example, you may want to drop all rows in a dataframe that contain missing values. Or keep only those rows that have a value that meets a particular condition.
+ **sort** - arrange the dataframe in a particular order. For example, you may want to sort a dataframe by a year or time column to arrange each row in chronological order. You may also sort a dataframe by multiple columns at once (i.e. sorting by year first and country second).
    <img src = "https://pythonexamples.org/images/python-pandas-dataframe-sort-by-index.svg" style = "width:40%">

Some examples of how you may want to subset, filter, or sort this lesson's dataframes: 

| Modification | World Cup dataset | Gapminder dataset | Film Dialogue dataset |
| :- | :- | :- | :- |
| **subset / filter** | create a df including only the 21st century men's World Cup champions | only review data from a set number of countries **or** for set range of years | keep only "title", "gender", and "proportion_of_dialogue" columns **or** only include data for film dialogue spoken by a character over 50 years old  |
| **sort** | Sort dataframe by year, but this time in ascending order | sort dataframe by life expectancy in 2007, in descending order | sort df by proportion of dialogue |

In [753]:
film_dialogue_df.columns

Index(['script_id', 'imdb_character_name', 'words', 'gender', 'age', 'imdb_id',
       'title', 'year', 'gross', 'proportion_of_dialogue'],
      dtype='str')

In [754]:
print(sorted(gapminder_df["year"].unique()))
print(min(gapminder_df["year"]))
max(gapminder_df["year"])

[np.int64(1952), np.int64(1957), np.int64(1962), np.int64(1967), np.int64(1972), np.int64(1977), np.int64(1982), np.int64(1987), np.int64(1992), np.int64(1997), np.int64(2002), np.int64(2007)]
1952

2007

### Vb. Subsetting / Filtering

13. We can create data subsets by using the same slicing functions described in Part IV and saving them as new dataframes. For example:

In [755]:
gapminder_subset = gapminder_df[0:10]
gapminder_subset.shape

(10, 6)

<div class="alert alert-success" role="alert"><p style="color:green">13b. Let's take a look at the film_df again by using the .head() method.</p></div>

In [757]:
film_dialogue_df.head(2)

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
0,280,betty,311,f,35.00,tt0112579,The Bridges of Madison County,1995,142.00,0.05
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.14

13c. We can simplify things by only keeping the columns we need. 

Below are two different ways to subset by a dataframe by column name.

In [758]:
film_subset = film_dialogue_df[['year', 'title', 'gender','proportion_of_dialogue']]
film_subset.head()

# notice: in the 1st line of code above, we not only selected 3 columns to keep but we also re-arranged their order!

   year                          title gender  proportion_of_dialogue
0  1995  The Bridges of Madison County      f                    0.05
1  1995  The Bridges of Madison County      f                    0.14
2  1995  The Bridges of Madison County      f                    0.02
3  1995  The Bridges of Madison County      f                    0.35
4  1995  The Bridges of Madison County      f                    0.03

In [759]:
#note: this does the same as above, only this time using the .loc[] method
film_subset = film_dialogue_df.loc[:,['year', 'title', 'gender', 'age', 'proportion_of_dialogue']]
film_subset.head()

   year                          title gender   age  proportion_of_dialogue
0  1995  The Bridges of Madison County      f 35.00                    0.05
1  1995  The Bridges of Madison County      f   NaN                    0.14
2  1995  The Bridges of Madison County      f   NaN                    0.02
3  1995  The Bridges of Madison County      f 46.00                    0.35
4  1995  The Bridges of Madison County      f 46.00                    0.03

15. Wee may want to drop observations (rows) containing null data (warning: you should always consider what this removal does to the representative nature of your dataset!). We can use the **.dropna()** method. See some examples below:

In [760]:
print(film_subset.shape)
film_subset_no_nas = film_subset.dropna()
print(film_subset_no_nas.shape)

(23048, 5)
(18263, 5)

15b. Temporarily or permanently changing a dataframe: Most methods in Python just temporarily change a dataframe unless you assign the modified dataframe to a variable. For example:

```
film_dialogue_df.dropna()
```
just outputs a version of film_df with all NAs and null values removed, but does not save it to memory. If we wanted to replace the original "film_df" we can simply assign it the same name as follows:

```
film_dialogue_df = film_df.dropna()
```
Or we can save it under a new name as we did above:
```
film_df_no_nas = film_dialogue_df.dropna()
```

Finally, we can also use the "inplace" argument to do the same:

```
film_dialogue_df.dropna(inplace = True)
```

15d. More commonly, you may want to remove rows that are missing values for specific columns. For example, if you want to analyze the age of characters / actors given speaking roles in films, you would want to remove any characters (rows) for which we lack age data.

In [761]:
film_subset.info()

<class 'pandas.DataFrame'>
RangeIndex: 23048 entries, 0 to 23047
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   year                    23048 non-null  int64
 1   title                   23048 non-null  str
 2   gender                  23048 non-null  str
 3   age                     18263 non-null  float64
 4   proportion_of_dialogue  23048 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 900.4 KB

In [762]:
print(film_subset.shape)
film_subset = film_subset.dropna(subset = "age")
print(film_subset.shape)

(23048, 5)
(18263, 5)

### Vc. Filtering a dataframe by a condition

16a. To filter a dataframe by a condition, first we need to define the filter itself:

In [763]:
film_subset['year'] == 1995   #remember: "=" indicates an assignment and "==" indicates a comparison returning True if both sides are equal and False if not

0         True
3         True
4         True
5         True
6         True
         ...
23043    False
23044    False
23045    False
23046    False
23047    False
Name: year, Length: 18263, dtype: bool

16b. We can then assign this specific filter to a variable...

In [764]:
filter = (film_dialogue_df['year'] == 1995)

16c. And use that filter to create a subset of our original dataset

In [765]:
df_1995 = film_dialogue_df.loc[filter]
df_1995.head(3)

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
0,280,betty,311,f,35.00,tt0112579,The Bridges of Madison County,1995,142.00,0.05
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.14
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.02

16d. We can also filter by multiple conditions:

In [766]:
years_filt = (film_dialogue_df['year'] >= 1990) & (film_dialogue_df['year'] < 2000)
nineties_films = film_dialogue_df.loc[years_filt]     #note: you cannot begin a variable name with a number, thus 90s_films would raise an error
nineties_films.shape

(5838, 10)

We can also combine multiple filters to create an even smaller and more specific subset:

In [767]:
gross_filt = (film_dialogue_df['gross'] > 800)
nineties_blockbusters = film_dialogue_df.loc[years_filt & gross_filt]
nineties_blockbusters

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
8066,2690,dennis nedry,584,m,38.00,tt0107290,Jurassic Park,1993,844.00,0.05
8067,2690,donald gennaro,509,m,46.00,tt0107290,Jurassic Park,1993,844.00,0.04
8068,2690,dr. alan grant,2550,m,46.00,tt0107290,Jurassic Park,1993,844.00,0.21
8069,2690,dr. ellie sattl,1434,f,26.00,tt0107290,Jurassic Park,1993,844.00,0.12
8070,2690,dr. ian malcolm,1317,m,41.00,tt0107290,Jurassic Park,1993,844.00,0.11
...,...,...,...,...,...,...,...,...,...,...
15331,5136,scotland road s,154,m,NaN,tt0120338,Titanic,1997,1249.00,0.01
15332,5136,spicer lovejoy,287,m,56.00,tt0120338,Titanic,1997,1249.00,0.02
15333,5136,thomas andrews,559,m,48.00,tt0120338,Titanic,1997,1249.00,0.04
15334,5136,tommy ryan,166,m,25.00,tt0120338,Titanic,1997,1249.00,0.01
15335,5136,woman,116,f,52.00,tt0120338,Titanic,1997,1249.00,0.01

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part V. Subsets and Filters</h3>

<p style="color:blue;">17. Filter and subset the film_df to create a new dataset with only films from **a decade of your choosing**.</p>
</div>

In [768]:
years_filt = (film_dialogue_df['year'] >= 1970) & (film_dialogue_df['year'] < 1980)
seventies_films = film_dialogue_df.loc[years_filt] 
print(seventies_films.describe())  #we need a print() function to output this code b/c it is not the last line of code
seventies_films.head()  #as the last line of code in the cell, this will automatically output without a print() function

       script_id    words    age    year   gross  proportion_of_dialogue
count    1109.00  1109.00 897.00 1109.00  340.00                 1109.00
mean     4563.66   796.81  41.50 1974.83  424.25                    0.09
std      2470.47  1179.07  12.66    2.91  388.40                    0.12
min       666.00   101.00   8.00 1970.00    6.00                    0.00
25%      2328.00   181.00  32.00 1972.00  148.50                    0.02
50%      4489.00   355.00  40.00 1975.00  374.50                    0.04
75%      6958.00   882.00  50.00 1977.00  559.75                    0.10
max      8901.00 12487.00  88.00 1979.00 1798.00                    0.88

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
196,666,bob falfa,248,m,31.00,tt0069704,American Graffiti,1973,565.00,0.03
197,666,budda,226,f,22.00,tt0069704,American Graffiti,1973,565.00,0.02
198,666,carlos,131,m,18.00,tt0069704,American Graffiti,1973,565.00,0.01
199,666,carol,729,f,14.00,tt0069704,American Graffiti,1973,565.00,0.07
200,666,curt,1240,m,26.00,tt0069704,American Graffiti,1973,565.00,0.13

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part Vb: Subsetting</h3>

<p style="color:blue;">17b. Using the methods you learned above, what are some different ways you could go about subsetting and filtering the gapminder dataset so that it includes only data from Asia and only for the twenty-first century.</p>
</div>

Write some possible solutions here: 

* filter the "continent" column to save only rows where continent == "Asia"
* keep only the columns: "continent", "country", and the gdpPercap, lifeExp, and pop columns from 2002 and 2007.

<div class="alert alert-info" role="alert"><p style="color:blue;">17c. Implement one of your proposed solutions above to subset the gapminder dataset as described in 17b.</p></div>

In [769]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

In [770]:
cont_filt = (gapminder_df['continent'] == "Asia")
year_filt = (gapminder_df['year'] >= 2000)
#year_filt = (gapminder_df['year'].between(2002, 2007))
gapminder_Asia_21C = gapminder_df[cont_filt & year_filt]

gapminder_Asia_21C

                 country continent  year  lifeExp        pop  gdpPercap
10           Afghanistan      Asia  2002    42.13   25268405     726.73
11           Afghanistan      Asia  2007    43.83   31889923     974.58
94               Bahrain      Asia  2002    74.80     656397   23403.56
95               Bahrain      Asia  2007    75.64     708573   29796.05
106           Bangladesh      Asia  2002    62.01  135656790    1136.39
...                  ...       ...   ...      ...        ...        ...
1655             Vietnam      Asia  2007    74.25   85262356    2441.58
1666  West Bank and Gaza      Asia  2002    72.37    3389578    4515.49
1667  West Bank and Gaza      Asia  2007    73.42    4018332    3025.35
1678         Yemen, Rep.      Asia  2002    60.31   18701257    2234.82
1679         Yemen, Rep.      Asia  2007    62.70   22211743    2280.77

[66 rows x 6 columns]

### Vd. Sorting a dataframe

18. We can sort a dataframe by the values in one column or in multiple columns using the **.sortvalues()** method.

In [771]:
film_dialogue_df.sort_values(by = ['year'])

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
12345,4031,polly,386,f,28.00,tt0019777,The Cocoanuts,1929,NaN,0.05
12344,4031,penelope,534,f,24.00,tt0019777,The Cocoanuts,1929,NaN,0.06
12343,4031,mrs. potter,492,f,47.00,tt0019777,The Cocoanuts,1929,NaN,0.06
12341,4031,chico,915,m,42.00,tt0019777,The Cocoanuts,1929,NaN,0.11
12340,4031,bob,668,m,42.00,tt0019777,The Cocoanuts,1929,NaN,0.08
...,...,...,...,...,...,...,...,...,...,...
18857,7207,cassandra,122,f,51.00,tt2231253,Wild Card,2015,NaN,0.02
18856,7207,baby,379,m,55.00,tt2231253,Wild Card,2015,NaN,0.06
15960,5390,abby gerhard,608,f,41.00,tt2402927,Carol,2015,NaN,0.07
15961,5390,carol aird,3499,f,46.00,tt2402927,Carol,2015,NaN,0.37
18860,7207,dd,308,f,43.00,tt2231253,Wild Card,2015,NaN,0.05

19. We can sort columns in descending order by adding the argument ```ascending = False``` (the default is "ascending = True").

In [772]:
film_dialogue_df.sort_values(by = ['year'], ascending = False)

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
20367,7858,shitnts,144,m,NaN,tt2561572,Get Hard,2015,93.00,0.01
20366,7858,Russell,772,m,35.00,tt2561572,Get Hard,2015,93.00,0.07
20365,7858,rita,448,f,NaN,tt2561572,Get Hard,2015,93.00,0.04
19661,7545,detective john,961,m,56.00,tt2199571,Run All Night,2015,27.00,0.13
19660,7545,colin,484,m,NaN,tt2199571,Run All Night,2015,27.00,0.06
...,...,...,...,...,...,...,...,...,...,...
12341,4031,chico,915,m,42.00,tt0019777,The Cocoanuts,1929,NaN,0.11
12344,4031,penelope,534,f,24.00,tt0019777,The Cocoanuts,1929,NaN,0.06
12345,4031,polly,386,f,28.00,tt0019777,The Cocoanuts,1929,NaN,0.05
12342,4031,hammer,5577,m,39.00,tt0019777,The Cocoanuts,1929,NaN,0.65
12343,4031,mrs. potter,492,f,47.00,tt0019777,The Cocoanuts,1929,NaN,0.06

19b. When sorting by multiple columns, we need to specify which will be sorted in ascending rather than descending order using a list of the same length as the list of columns.

In [773]:
film_dialogue_df.sort_values(by = ['year', 'title', 'imdb_character_name'], ascending = [False, True, True])

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
19998,7716,adrian yates,1833,m,37.00,tt3316948,American Ultra,2015,14.00,0.22
19999,7716,krueger,386,m,62.00,tt3316948,American Ultra,2015,14.00,0.05
20000,7716,laugher,105,m,44.00,tt3316948,American Ultra,2015,14.00,0.01
20001,7716,mike howell,1931,m,32.00,tt3316948,American Ultra,2015,14.00,0.24
20002,7716,otis,226,m,51.00,tt3316948,American Ultra,2015,14.00,0.03
...,...,...,...,...,...,...,...,...,...,...
12341,4031,chico,915,m,42.00,tt0019777,The Cocoanuts,1929,NaN,0.11
12342,4031,hammer,5577,m,39.00,tt0019777,The Cocoanuts,1929,NaN,0.65
12343,4031,mrs. potter,492,f,47.00,tt0019777,The Cocoanuts,1929,NaN,0.06
12344,4031,penelope,534,f,24.00,tt0019777,The Cocoanuts,1929,NaN,0.06
12345,4031,polly,386,f,28.00,tt0019777,The Cocoanuts,1929,NaN,0.05

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercise for Part Vd. Sorting</h3>

<p style="color:blue;">20. Sort the gapminder dataframe by first the "continent" column and then the "country" column, but in descending (not ascending) order for each.</p></div>

In [774]:
gapminder_df.sort_values(by = ['continent', 'country'], ascending = [False, False])

          country continent  year  lifeExp       pop  gdpPercap
1092  New Zealand   Oceania  1952    69.39   1994794   10556.58
1093  New Zealand   Oceania  1957    70.26   2229407   12247.40
1094  New Zealand   Oceania  1962    71.24   2488550   13175.68
1095  New Zealand   Oceania  1967    71.52   2728150   14463.92
1096  New Zealand   Oceania  1972    71.89   2929100   16046.04
...           ...       ...   ...      ...       ...        ...
31        Algeria    Africa  1987    65.80  23254956    5681.36
32        Algeria    Africa  1992    67.74  26298373    5023.22
33        Algeria    Africa  1997    69.15  29072015    4797.30
34        Algeria    Africa  2002    70.99  31287142    5288.04
35        Algeria    Africa  2007    72.30  33333216    6223.37

[1704 rows x 6 columns]

<div class="alert alert-info" role="alert"><p style="color:blue;">20b. Sort the Gapminder dataframe in three ways to answer the following three questions:</p>
<ul>
<li style = "color:blue;">Which five countries had the largest population in 2007?</li>
<li style = "color:blue;">Which five countries had the highest GDP in 2007?</li>
<li style = "color:blue;">Which five countries had the highest life expectancy in 2007?</li>
</ul>
</div>

In [775]:
gapminder_df[["continent", "country", "year", "pop"]].sort_values(by = "pop", ascending = False)

     continent                country  year         pop
299       Asia                  China  2007  1318683096
298       Asia                  China  2002  1280400000
297       Asia                  China  1997  1230075000
296       Asia                  China  1992  1164970000
707       Asia                  India  2007  1110396331
...        ...                    ...   ...         ...
1299    Africa  Sao Tome and Principe  1967       70787
1298    Africa  Sao Tome and Principe  1962       65345
420     Africa               Djibouti  1952       63149
1297    Africa  Sao Tome and Principe  1957       61325
1296    Africa  Sao Tome and Principe  1952       60011

[1704 rows x 4 columns]

In [776]:
year_filt = (gapminder_df['year'] == 2007)
gapminder_df.loc[year_filt, ["continent", "country", "gdpPercap"]].sort_values(by = "gdpPercap", ascending = False).head()

     continent        country  gdpPercap
1151    Europe         Norway   49357.19
863       Asia         Kuwait   47306.99
1367      Asia      Singapore   47143.18
1619  Americas  United States   42951.65
755     Europe        Ireland   40676.00

In [777]:
year_filt = (gapminder_df['year'] == 2007)
gapminder_df.loc[year_filt, ["continent", "country", "lifeExp"]].sort_values(by = "lifeExp", ascending = False).head()

     continent           country  lifeExp
803       Asia             Japan    82.60
671       Asia  Hong Kong, China    82.21
695     Europe           Iceland    81.76
1487    Europe       Switzerland    81.70
71     Oceania         Australia    81.23

## VII. Split-Apply-Combine

<img src = "https://www.oreilly.com/api/v2/epubs/9781783985128/files/graphics/5128OS_09_01.jpg" style="width:40%">

A commonly used data analysis strategy is **split-apply-combine**:
+ **split** the problem / data into manageable pieces
+ **apply** some calculations or analysis to the pieces
+ **combine** the parts back into a whole

For computational data science this means (from [Python Pandas documentation](https://pandas.pydata.org/docs/user_guide/groupby.html)):
```
    * Splitting the data into groups based on some criteria
    * Applying a function to each group independently
    * Combining the results into a data structure
```

Let's examine how this strategy may work for the datasets we have been working with. In our Gapminder dataset, for example, we may want to explore larger trends at the continent level. So we could:
+ **split** the overall dataset by continent, creating separate Africa, Asia, North America, South America, Oceania, and Europe datasets.
+ **apply** some calculations to each continental dataset; i.e. What is the average GDP and life expectancy of each continent in different years? Or what has been the average rate of change in these values from one five year interval to the next?
+ **combine** the data back together to compare changes in productivity (as measured by GDP) and health (as measured by life expectancy) by continent and over time.

Different applications apply this strategy in different ways. In Excel, you would use pivot tables, SQL the "group by" operator, and in R you may use the plyr package.

With Pandas, we can use the **.groupby()**, **.agg()**, and **.apply()** functions to do this. 
+ **.groupby()** - *splits* a dataset into separate groups
+ **.agg()** - used to calculate multiple statistics per group in one calculation
+ **.apply()** - applies a function across an entire column (or row) in a Pandas dataframe

Let's re-examine the contents of our Gapminder dataframe. 

27. Use the .head() method to output its first five rows and use the .columns method to output summary information about this dataframe.

In [778]:
gapminder_df.head()

       country continent  year  lifeExp       pop  gdpPercap
0  Afghanistan      Asia  1952    28.80   8425333     779.45
1  Afghanistan      Asia  1957    30.33   9240934     820.85
2  Afghanistan      Asia  1962    32.00  10267083     853.10
3  Afghanistan      Asia  1967    34.02  11537966     836.20
4  Afghanistan      Asia  1972    36.09  13079460     739.98

In [779]:
gapminder_df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='str')

### VIIb: Groupby()

*This first few cells of this section are adapted from Constellate's [3rd Pandas tutorial](https://lab.constellate.org/practical-diabetes-methods/notebooks/tdm-notebooks-2023-04-20T12%3A35%3A07.477Z/pandas-3.ipynb).*

28. Groupby is a powerful function built into Pandas that you can use to summarize your data. Groupby splits the data into different groups on a variable of your choice. 

To learn more about using Pandas **.groupby()** to split-apply-combine data, see the [documentation here](https://pandas.pydata.org/docs/user_guide/groupby.html).

In [780]:
# Group the data by continent
gapminder_df.groupby('continent')

29. The groupby() method returns a GroupBy object which describes how the rows of the original dataset have been split by the selected variable. You can actually see how the rows of the original dataframe have been grouped using the ```groups``` attribute after applying ```groupby().```

In [781]:
# See how the rows have been grouped
gapminder_df.groupby('continent').groups
#Note: this dataset had already been sorted by continent.

{'Africa': [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, ...], 'Americas': [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 432, 433, 434, 435, ...], 'Asia': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, ...], 'Europe': [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 516, 517, 518, 519, ...], 'Oceania': [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099, 1100, 1101, 1102, 1103]}

30. Of course, we don't just stop at grouping data. Grouping data is just a step towards data query. After we apply the .groupby() method, we can actually use different Pandas methods to query the data. For example, how do we get the number of documents in each docType by publicationYear?

In [782]:
# Create a series storing the number of documents in each doc type by year
gapminder_df.groupby('continent').size()

continent
Africa      624
Americas    300
Asia        396
Europe      360
Oceania      24
dtype: int64

We can then use the **.agg()** (aggregate) method to choose what functions we will **apply** to each group to allow us to **combine** the data back together.

The general formula for applying functions using the aggregate (.agg()) method:

```
df_name.groupby('col_name').agg({dict assigning a function to each column we want to aggregate})

```
where the format for each dictionary is as follows:
```
{'name_of_col1_to_keep': 'function_to_apply_to_this_col', 'name_of_col2_to_keep': 'function_to_apply_to_this_col'}
```

Some commonly used functions with groupby ([click here](https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html#computations-descriptive-stats) for a full list):
+ .count(), .mean(), .min(), .max(), .sum()

31. With this in mind, examine the following line of code. What do you guess it does? Run it and see if you were correct?

In [783]:
year_filt = (gapminder_df['year'] == 2002)
gapminder_df.loc[year_filt, :].groupby('continent').agg({'lifeExp':'mean'})

           lifeExp
continent
Africa       53.33
Americas     72.42
Asia         69.23
Europe       76.70
Oceania      79.74

32. We can use the .agg() method to apply multiple functions to multiple columns:

In [784]:
# cont_pop_chg = gapminder_df.groupby('continent').agg({'pop_2002':'sum', 'pop_2007': 'sum'})
# cont_pop_chg

33. We can then use these two columns in the continental dataset to calculate percent population change between 2002 and 2007:

In [785]:
# cont_pop_chg['pct_chg_02-07'] = 100 * (cont_pop_chg['pop_2007'] - cont_pop_chg['pop_2002']) / cont_pop_chg['pop_2002']
# cont_pop_chg

<div class="alert alert-info" role="alert"><h3 style="color:blue;">Exercises Part VII: Split-Apply-Combine</h3></div>

<div class="alert alert-info" role="alert"><p style="color:blue;">34. Using what you learned above, group the film dialogue dataframe by gender and film and calculate the films in which women have the greatest percent of dialogue</p></div>

In [809]:
film_dialogue_df.head()

,script_id,imdb_character_name,words,gender,age,imdb_id,title,year,gross,proportion_of_dialogue
0,280,betty,311,f,35.00,tt0112579,The Bridges of Madison County,1995,142.00,0.05
1,280,carolyn johnson,873,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.14
2,280,eleanor,138,f,NaN,tt0112579,The Bridges of Madison County,1995,142.00,0.02
3,280,francesca johns,2251,f,46.00,tt0112579,The Bridges of Madison County,1995,142.00,0.35
4,280,madge,190,f,46.00,tt0112579,The Bridges of Madison County,1995,142.00,0.03

In [810]:
film_titles_female_speaking = film_dialogue_df.groupby(['title', 'gender']).agg({'proportion_of_dialogue':'sum', 'year': 'first'})
film_titles_female_speaking

                                   proportion_of_dialogue  year
title                      gender
(500) Days of Summer       f                         0.31  2009
                           m                         0.69  2009
10 Things I Hate About You f                         0.46  1999
                           m                         0.54  1999
12 Years a Slave           f                         0.18  2013
...                                                   ...   ...
Zodiac                     m                         0.90  2007
eXistenZ                   f                         0.40  1999
                           m                         0.60  1999
xXx                        f                         0.12  2002
                           m                         0.88  2002

[3936 rows x 2 columns]

In [811]:
film_titles_female_speaking = film_titles_female_speaking.reset_index()
film_titles_female_speaking.head()

                        title gender  proportion_of_dialogue  year
0        (500) Days of Summer      f                    0.31  2009
1        (500) Days of Summer      m                    0.69  2009
2  10 Things I Hate About You      f                    0.46  1999
3  10 Things I Hate About You      m                    0.54  1999
4            12 Years a Slave      f                    0.18  2013

In [818]:
film_titles_female_speaking = (
    film_titles_female_speaking[
    film_titles_female_speaking['gender'] == 'f']
    .sort_values(by="proportion_of_dialogue", ascending=False)
)

In [819]:
film_titles_female_speaking.groupby("year").agg({"proportion_of_dialogue": "mean"}).sort_values("proportion_of_dialogue", ascending=False)

      proportion_of_dialogue
year
1963                    0.65
1950                    0.46
1943                    0.45
1944                    0.41
1960                    0.38
...                      ...
1969                    0.11
1953                    0.11
1937                    0.11
1946                    0.09
1955                    0.05

[81 rows x 1 columns]